### ISSUE TITLE
Requests: Set title character limit to 200

### ISSUE THREAD

**Issue by danielfe** [microsoft/community-organization-operations-suite#310]
Right now the character limit on requests titles is too short, 50. Let's up it to 200. 

![image](https://user-images.githubusercontent.com/4665144/153914779-487cd55f-88e9-43b5-8205-153de56a6fad.png)

**Comment by ThomasKapler** [comment]
As of Mar 9, this issue is not resolved on staging version

**Comment by ThomasKapler** [comment]
Yohann, I noticed that this title field is only 1 row high now, which does not fit 200 chars and therefore makes it hard to read. Can you make height expand to fit the whole title or add more rows to the height?

**Comment by YohannParis** [comment]
This is becoming an UX issue, a title that is 200 characters long (longer than a Tweet) is not really a title! 
The user should rewritte its title and add a description. 
The 200 limits increase is mostly an insurance against long title, not sentences long titles

If I add an extra row, it will become a `<Textarea>` instead of an `<input>`. 

@danielfe what's your opinion on this?

**Comment by danielfe** [comment]
Sorry im late to the party. I think the use case here is not that far off from what we would want ourselves in a GitHub issue, but lets live on it for a while and see how folks use it
