### ISSUE TITLE
Some field inappropriately suggesting autofill with address

### ISSUE THREAD

**Issue by danielfe** [microsoft/community-organization-operations-suite#330]
Some fields in the client form are using the browser's autofill feature to suggest filling them with the user's contact info, when they should not. Let's disabled autofill for these fields. 

![image](https://user-images.githubusercontent.com/4665144/153920603-83d42ad7-c749-4fc9-9e20-819aac6d0fe0.png)

**Comment by YohannParis** [comment]
Fun fact, your browser offers to fill your **city** for the input _Ethni**city**_!
I love Regular Expressions like these.

**Comment by ThomasKapler** [comment]
Chrome ignores disabled autofill instructions - Need to do more research to resolve this privacy issue

**Comment by YohannParis** [comment]
- As of now the codebase has been updated to tell browser that `autocomplete=off`.
- If a user as specifically set up their browser preferences to autofill form fields with saved contact information, the browser will do so.
- We cannot override a user's browser's preferences unless using bad field names to trick the browser. This will make the codebase harder to maintain.

I do believe that this issue is closed.

**Comment by danielfe** [comment]
Boooo Chrome. Thanks for looking into this Yohann and Tom. I would recommend we go with 1. Let’s not change the name. It’s reasonable for now to ask them to make sure they arent putting their own info a clients record. We can revisit if we get user feedback on this, but we have not so far.

**Comment by YohannParis** [comment]
Great!

To be fair, this behaviour is on all browser as it is what a user expect from it.
