### ISSUE TITLE
Paper 2.0 Requirements

### ISSUE THREAD

**Issue by DChen602** [microsoft/community-organization-operations-suite#361]

**Comment by danielfe** [comment]
Research for Paper 2.0 is complete. Six ideas came out. 

Practice Mode (#464)
OCR - scan handwriting back into HCH (#514 , many other cases need to be filed)
Offline data entry (#407)
A concierge service for creating forms
File attachment (#486)
Voice notes

**Comment by danielfe** [comment]
I am marking this issue as complete. You can see the results of our discovery process here:
https://docs.google.com/presentation/d/1UYAQgSMnG35dUsHOy32OHX9wMX9nLg0XL7pTksa978w/edit#slide=id.p

This effort resulted in four features being added to the backlog. Two of which are in development at time of writing:
407 - Offline mode. The ability to get to and write critical records without an internet connection. 
464 - A practice mode where you can try HCH without fear of messing up
514 - Paper scanning with your cell phone camera (OCR)
486 - File attachments, associated with a client, service record or request.

We also created these two concepts though because there wasn't as much demand and there are open questions, we didnt add them to the roadmap as their own cards. 
- Ability to take voice notes on your phone
- An agent who can help you create services, possibly for a fee
