### ISSUE TITLE
Filtering service records by client tags does not work

### ISSUE THREAD

**Issue by danielfe** [microsoft/community-organization-operations-suite#426]
SUMMARY
Client tags is a column that is available on the reporting page when you are looking at entries for a service. However when you try to filter by those tags, nothing happens. The rows are not filtered. 

STEPS TO REPRODUCE
- Go to reporting page
- Click on the pulldown and choose services
- Choose a service (choose one that is linked to clients and has clients with tags)
- Find the Client Tags column
- Click the filter button on that column
- Click a checkbox to filter on that tag

RESULTS
Expected - the rows filter to only show service entries where the client is tagged with the tag I chose
Actual - rows are not filtered at all

VIDEO
https://www.loom.com/share/dd21b94c8d9f4643aad654de823a0c22

NOTES
This seems particular to client tags. You can successfully filter on other client fields

**Comment by ThomasKapler** [comment]
Nice catch!

**Comment by ThomasKapler** [comment]
Hey, this is actually working for me no problem... on chrome and safari on ipad and windows/chrome. From the video it looks like it may be some other problem: i.e. the filter works, but it doesn't stick. The table does shows the right filter state for a moment, but then immediately reverts back. So the issue is not the filter itself, but some problem with updating that is not consistent among testers. Daniel - Looks like that was safari on a mac, right. I can't test that...

**Comment by ThomasKapler** [comment]
@danielfe Hi Daniel - see comment above...

**Comment by ThomasKapler** [comment]
Just testing again and the tag filters are not working now. I swear I saw this working at one point. Hopefully engineering can repro when they start looking at this

**Comment by karlolsonuc** [comment]
Can't seem to get repro any more on local, integration or demo.

**Comment by danielfe** [comment]
Just reproduced on demo. Filtering clients works. What doesn't work is filtering service rows by a client tag.
